name: Flink Client CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Docker
      run: sh pipeline/setup-docker.sh
    - name: Build and run tests
      run: mvn -t toolchains.xml clean verify
